Add delay between request to reduce stress on theatre classique server

diff --git a/update b/update
--- a/update
+++ b/update
@@ -8,6 +8,7 @@ Usage: $0 [--all | --help]
 
 OPTIONS:
   -a, --all       update all files including existing ones
+  -d, --delay     number of seconds to wait between requests (default: 1)
   -h, --help      show this message
 
 EOF
@@ -18,6 +19,7 @@ EOF
 
 ALL=""
 PARAMS=""
+DELAY=1
 
 while (( "$#" )); do
   case "$1" in
@@ -32,6 +34,20 @@ while (( "$#" )); do
     -v|--verbose)
       VERBOSE=yes
       shift
+      ;;
+    -d|--delay)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        re='^[0-9.]+$'
+        if ! [[ $2 =~ $re ]]; then
+          echo "Delay must be a number!"
+          exit 1
+        fi
+        PORT=$2
+        shift 2
+      else
+        echo "Error: Argument for $1 is missing" >&2
+        exit 1
+      fi
       ;;
     -*|--*=) # unsupported flags
       echo "Error: Unsupported flag $1" >&2
@@ -84,6 +100,8 @@ for url in $($LYNX | $GREP); do
       # abort on other errors
       exit 1
     fi
+    [ -z $VERBOSE ] || echo "waiting $DELAY seconds..."
+    sleep $DELAY
   else
     [ -z $VERBOSE ] || echo "skipping $name"
   fi
